import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ReduxProvider } from '@/redux/ReduxProvider'
import TokenExpirationChecker from './components/TokenExpirationChecker/TokenExpirationChecker'
import Header from './components/Header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Header />
          <TokenExpirationChecker minutes={1} />
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
